Laptop/Models/laptop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laptop
    {
        public int ID { get; set; }
        public string Company { get; set; }
        public string Product { get; set; }
        public string TypeName { get; set; }
        public Nullable<double> Inches { get; set; }
        public string ScreenResolution { get; set; }
        public string Cpu { get; set; }
        public string Gen { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<int> Ram { get; set; }
        public string Memory { get; set; }
        public string Gpu { get; set; }
        public string OpSys { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Price_euros { get; set; }
    }
}

Laptop/Controllers/LaptopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laptop.Models;

namespace Laptop.Controllers
{
    public class LaptopController : Controller
    {
        TMDT5Entities db = new TMDT5Entities();
        // GET: Laptop 
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult getCompany()
        {
            var ListCompany = db.laptops.GroupBy(l => l.Company).Select(l => l.Key);
            return PartialView(ListCompany);
        }
        public ActionResult getCPU()
        {
            var ListCPU = db.laptops.GroupBy(l => l.Cpu).Select(l => l.Key);
            return PartialView(ListCPU);
        }
        public ActionResult getScreenResolution()
        {
            var ListScreenResolution = db.laptops.GroupBy(l => l.ScreenResolution).Select(l => l.Key);
            return PartialView(ListScreenResolution);
        }
        public ActionResult getTypeName()
        {
            var ListTypeName = db.laptops.GroupBy(l => l.TypeName).Select(l => l.Key);
            return PartialView(ListTypeName);
        }
        public ActionResult getInches()
        {
            var ListInches = db.laptops.GroupBy(l => l.Inches).Select(l => l.Key.ToString());
            return PartialView(ListInches);
        }
        public ActionResult getSpeed()
        {
            var ListSpeed = db.laptops.GroupBy(l => l.Speed).Select(l => l.Key.ToString());
            return PartialView(ListSpeed);
        }
        public ActionResult getMemory()
        {
            var ListMemory = db.laptops.GroupBy(l => l.Memory).Select(l => l.Key);
            return PartialView(ListMemory);
        }
        public ActionResult getRam()
        {
            var ListRam = db.laptops.GroupBy(l => l.Ram).Select(l => l.Key);
            return PartialView(ListRam);
        }
        public ActionResult getWeight()
        {
            var ListWeight = db.laptops.GroupBy(l => l.Weight).Select(l => l.Key);
            return PartialView(ListWeight);
        }
        public ActionResult getGpu()
        {
            var ListGpu = db.laptops.GroupBy(l => l.Gpu).Select(l => l.Key);
            return PartialView(ListGpu);
        }


        /// Sv tự thêm các thông tin khác 
    }
}

Laptop/Views/Laptop/Index.cshtml
@model IEnumerable<Laptop.Models.laptop>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@{Html.RenderAction("getCompany", "Laptop"); }
<br />
@{Html.RenderAction("getCPU", "Laptop"); }
<br />
@{Html.RenderAction("getScreenResolution", "Laptop");}
<br />
@{Html.RenderAction("getTypeName", "Laptop");}
<br />
@{Html.RenderAction("getGpu", "Laptop");}
@{Html.RenderAction("getInches", "Laptop"); }
<br />
@{Html.RenderAction("getSpeed", "Laptop"); }
    @*@{Html.RenderAction("getMemory", "Laptop");}
    <br />
    
    @{Html.RenderAction("getRam", "Laptop");}
    <br />
    @{Html.RenderAction("getSpeed", "Laptop"); }
    @*<br />
    @{Html.RenderAction("getWeight", "Laptop");}*@


<input type="button" name="name" onclick="find();" value="Assign" />
<ul id="laptop"></ul>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>


    var uri = "../../api/LaptopAPI"
    $(document).ready(function () {
        $.getJSON(uri).done(function (data) {
            $.each(data, function (key, item) {
                $('<li>', { text: formatItem(item) }).appendTo($('#laptop'));
            });
        });

    });
    function formatItem(item) {
        return item.Product + ':' + item.ScreenResolution;
    }
    function find() {
        $('#laptop').text('');
        var idString = "";
        var idCompany = $('#2').find('input[type=checkbox]');
        for (var i = 0; i < idCompany.length; i++) {
            if (idCompany[i].checked) {
                if (idString == "") {
                    idString = "2-" + idCompany[i].name;
                }
                else {
                    idString = idString + "_2-" + idCompany[i].name;
                }
            }
        }
        var idCPU = $('#6').find('input[type=checkbox]');
        for (var i = 0; i < idCPU.length; i++) {
            if (idCPU[i].checked) {
                if (idString == "") {
                    idString = "6-" + idCPU[i].name;
                }
                else {
                    idString = idString + "_6-" + idCPU[i].name;
                }
            }
        }
        var idScreen = $('#3').find('input[type=checkbox]');
        for (var i = 0; i < idScreen.length; i++) {
            if (idScreen[i].checked) {
                if (idString == "") {
                    idString = "3-" + idScreen[i].name;
                }
                else {
                    idString = idString + "_3-" + idScreen[i].name;
                }
            }
        }
        var idTypeName = $('#4').find('input[type=checkbox]');
        for (var i = 0; i < idTypeName.length; i++) {
            if (idTypeName[i].checked) {
                if (idString == "") {
                    idString = "4-" + idTypeName[i].name;
                }
                else {
                    idString = idString + "_4-" + idTypeName[i].name;
                }
            }
        }
        var idGpu = $('#10').find('input[type=checkbox]');
        for (var i = 0; i < idGpu.length; i++) {
            if (idGpu[i].checked) {
                if (idString == "") {
                    idString = "10-" + idGpu[i].name;
                }
                else {
                    idString = idString + "_10-" + idGpu[i].name;
                }
            }
        }
        var idInches = $('#5').find('input[type=checkbox]');
        for (var i = 0; i < idInches.length; i++) {
            if (idInches[i].checked) {
                if (idString == "") {
                    idString = "5-" + idInches[i].name;
                }
                else {
                    idString = idString + "_5-" + idInches[i].name;
                }
            }
        }
        var idSpeed = $('#7').find('input[type=checkbox]');
        for (var i = 0; i < idSpeed.length; i++) {
            if (idSpeed[i].checked) {
                if (idString == "") {
                    idString = "7-" + idSpeed[i].name;
                }
                else {
                    idString = idString + "_7-" + idSpeed[i].name;
                }
            }
        }
        @*
        var idMemory = $('#8').find('input[type=checkbox]');
        for (var i = 0; i < idMemo.length; i++) {
            if (idMemory[i].checked) {
                if (idString == "") {
                    idString = "8-" + idMemory[i].name;
                }
                else {
                    idString = idString + "_8-" + idMemory[i].name;
                }
            }
        }
        var idRam = $('#9').find('input[type=checkbox]');
        for (var i = 0; i < idRam.length; i++) {
            if (idRam[i].checked) {
                if (idString == "") {
                    idString = "9-" + idRam[i].name;
                }
                else {
                    idString = idString + "_9-" + idRam[i].name;
                }
            }
        }
        var idWeight  = $('#14').find('input[type=checkbox]');
        for (var i = 0; i < idWeight.length; i++) {
            if (idWeight[i].checked) {
                if (idString == "") {
                    idString = "14-" + idWeight[i].name;
                }
                else {
                    idString = idString + "_14-" + idWeight[i].name;
                }
            }
        }

            *@
        $.getJSON(uri + "/" + idString).done(function (data) {
            $.each(data, function (key, item) {
                $('<li>', { text: formatItem(item) }).appendTo($('#laptop'));
            });
        }).fail(function (jqXHR, textStatus, err) {
            $('#laptop').text('Error:' + err);
        });

    }
</script>

Laptop/Views/Laptop/getCPU.cshtml
@model IEnumerable<string>
<div id="6">
    @foreach (var item in Model)
    {
        @Html.CheckBox(item);
        @Html.Label(item);
        <b>&nbsp;</b>

    }
</div>

Laptop/Views/Laptop/getCompany.cshtml
@model IEnumerable<string>
    <div id="2">
        @foreach (var item in Model)
        {
            @Html.CheckBox(item);
            @Html.Label(item);
            <b>&nbsp;</b>

        }
    </div>

Laptop/Views/Laptop/getGpu.cshtml
@model IEnumerable<string>
<div id="10">
    @foreach (var item in Model)
    {
        @Html.CheckBox(item);
        @Html.Label(item);
        <b>&nbsp;</b>

    }
</div>

Laptop/Views/Laptop/getInches.cshtml
@model IEnumerable<string>
<div id="5">
    @foreach (var item in Model)
    {
        <input type="checkbox" name="Inches[]" value="@item"/>
        <span>@item</span>
        <b>&nbsp;</b>
    }
</div>

Laptop/Views/Laptop/getMemory.cshtml
@model IEnumerable<string>
<div id="8">
    @foreach (var item in Model)
    {
        @Html.CheckBox(item);
        @Html.Label(item);
        <b>&nbsp;</b>

    }
</div>

Laptop/Views/Laptop/getRam.cshtml
@model IEnumerable<string>
<div id="9">
    @foreach (var item in Model)
    {
        @Html.CheckBox(item);
        @Html.Label(item);
        <b>&nbsp;</b>

    }
</div>

Laptop/Views/Laptop/getScreenResolution.cshtml
@model IEnumerable<string>
<div id="3">
    @foreach (var item in Model)
    {
        @Html.CheckBox(item);
        @Html.Label(item);
        <b>&nbsp;</b>

    }
</div>

Laptop/Views/Laptop/getSpeed.cshtml
@model IEnumerable<string>
<div id="7">
    @foreach (var item in Model)
    {
        <input type="checkbox" name="Inches[]" value="@item" />
        <span>@item</span>
        <b>&nbsp;</b>
    }
</div>

Laptop/Views/Laptop/getTypeName.cshtml
@model IEnumerable<string>
<div id="4">
    @foreach (var item in Model)
    {
        @Html.CheckBox(item);
        @Html.Label(item);
        <b>&nbsp;</b>

    }
</div>

Laptop/Views/Laptop/getWeight.cshtml
@model IEnumerable<string>
<div id="14">
    @foreach (var item in Model)
    {
        @Html.CheckBox(item);
        @Html.Label(item);
        <b>&nbsp;</b>

    }
</div>